package com.example.speedtester.data.data_source.api

import okhttp3.MultipartBody
import okhttp3.ResponseBody
import retrofit2.Response
import retrofit2.http.GET
import retrofit2.http.Multipart
import retrofit2.http.POST
import retrofit2.http.Part
import retrofit2.http.Path

interface SpeedTestService {
    // This is the API to download 1MB file from the server http://speedtest.tele2.net/
    @GET("/{key}")
    suspend fun downloadTestFile(@Path("key") key: String): Response<ResponseBody>

    // This is the API to upload the file generated by the app and has a size of 1MB file to the server http://speedtest.tele2.net/
    @Multipart()
    @POST("/")
    suspend fun uploadTestFile(@Part file: MultipartBody.Part): Response<ApiUploadResponse>
}