package com.example.speedtester.data.data_source.api

import okhttp3.RequestBody
import okhttp3.ResponseBody
import retrofit2.Response
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.POST

interface SpeedTestService {
    // This is the API to download 1MB file from the server http://speedtest.tele2.net/
    @GET("1MB.zip")
    suspend fun downloadTestFile(): Response<ResponseBody>

    // This is the API to upload the file generated by the app and has a size of 1MB file to the server http://speedtest.tele2.net/
    @POST("upload")
    suspend fun uploadTestFile(@Body file: RequestBody): Response<ResponseBody>
}